### ISSUE TITLE
Ticking entity error caused by Gurty

### ISSUE THREAD

**Issue by Shenra123** [mactso/HarderFishesAndAmphibians#5]
Ever since the Gurty update I've been getting crashes. I'm not sure if it's actually caused by your mod but if I'm reading the crash report right then it should at least be related.

The crashes do not occur right away, generally I'll start a new world and move around a bit before it happens. In creative I can place a Gurty with a spawn egg and interact with it before it crashes but it eventually still does. It might have to do with the Gurty spawning naturally rather then the entity itself since I remember I went to a river to place them but I'm not sure.

[crash-2021-01-28_15.07.21-client.txt](https://github.com/mactso/HarderFishesAndAmphibians/files/5889732/crash-2021-01-28_15.07.21-client.txt)

**Comment by mactso** [comment]
I'll give this a look tomorrow morning.  Sorry about the problem!

It's definately the gurty.
I see it is version 1.16.5.  

Do you have the worldseed so I can test this where you were testing?

Some kind of client side code is being run on the server.   This should be fixed within 24 hours.

**Comment by mactso** [comment]
This should be fixed.   I found the error (in the preventdespawn routine).

For some reason the client also calls the preventdespawn routine.
Gurty's try to keep from despawning up to 3 gurties under certain circumstances.

**Comment by Shenra123** [comment]
Thanks for the fix! I'm glad my issue helped you fix an error.
I like your mod btw, it adds a lot to my rivers and swamps which are usually bare.

**Comment by mactso** [comment]
Your welcome!  We have a section for suggestions in discord.

There was a major update tonight which allows you better control over spawn rates of each hostile water mob.

How do you like the drops I wrote for this?
